export const BADGE_ICON_NAMES = [
  "building",
  "device",
  "bell",
  "box",
  "id-card",
  "key",
  "cloud",
  "graduation-cap",
  "target",
  "gear",
  "scroll",
  "shield-check",
  "refresh",
  "apple-mark",
  "trophy",
  "rocket",
  "crane",
  "plug",
  "landmark",
  "clipboard-check",
  "check-circle",
  "flask",
  "bolt",
  "star",
  "flame",
] as const;

export type BadgeIconName = (typeof BADGE_ICON_NAMES)[number];
